//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doopec.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Rtps : global::System.Configuration.ApplicationSettingsBase {
        
        private static Rtps defaultInstance = ((Rtps)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Rtps())));
        
        public static Rtps Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PB=7400, DG=250, PG=2, d0=0, d1=10, d2=1, d3=11")]
        public string PortConfig {
            get {
                return ((string)(this["PortConfig"]));
            }
        }
    }
}
