//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doopec.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Writer : global::System.Configuration.ApplicationSettingsBase {
        
        private static Writer defaultInstance = ((Writer)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Writer())));
        
        public static Writer Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PushMode {
            get {
                return ((bool)(this["PushMode"]));
            }
            set {
                this["PushMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5001")]
        public int HeartbeatPeriod {
            get {
                return ((int)(this["HeartbeatPeriod"]));
            }
            set {
                this["HeartbeatPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("201")]
        public int NackResponseDelay {
            get {
                return ((int)(this["NackResponseDelay"]));
            }
            set {
                this["NackResponseDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NackSuppressionDuration {
            get {
                return ((int)(this["NackSuppressionDuration"]));
            }
            set {
                this["NackSuppressionDuration"] = value;
            }
        }
    }
}
