using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Rtps.Discovery.Spdp
{
    [Flags]
    public enum BuiltinEndpointSet : uint
    {
        DISC_BUILTIN_ENDPOINT_PARTICIPANT_ANNOUNCER = 1 << 0,
        DISC_BUILTIN_ENDPOINT_PARTICIPANT_DETECTOR = 1 << 1,
        DISC_BUILTIN_ENDPOINT_PUBLICATION_ANNOUNCER = 1 << 2,
        DISC_BUILTIN_ENDPOINT_PUBLICATION_DETECTOR = 1 << 3,
        DISC_BUILTIN_ENDPOINT_SUBSCRIPTION_ANNOUNCER = 1 << 4,
        DISC_BUILTIN_ENDPOINT_SUBSCRIPTION_DETECTOR = 1 << 5,
        DISC_BUILTIN_ENDPOINT_PARTICIPANT_PROXY_ANNOUNCER = 1 << 6,
        DISC_BUILTIN_ENDPOINT_PARTICIPANT_PROXY_DETECTOR = 1 << 7,
        DISC_BUILTIN_ENDPOINT_PARTICIPANT_STATE_ANNOUNCER = 1 << 8,
        DISC_BUILTIN_ENDPOINT_PARTICIPANT_STATE_DETECTOR = 1 << 9,
        BUILTIN_ENDPOINT_PARTICIPANT_MESSAGE_DATA_WRITER = 1 << 10,
        BUILTIN_ENDPOINT_PARTICIPANT_MESSAGE_DATA_READER = 1 << 11
    }
}
